export const queryKeys = {
  providers: ['providers'] as const,
  providerModels: (id: string) => ['providers', id, 'models'] as const,
  agents: ['agents'] as const,
  agent: (id: string) => ['agents', id] as const,
  threads: ['threads'] as const,
  thread: (id: string) => ['threads', id] as const,
  runs: ['runs'] as const,
  tools: ['tools'] as const,
  tool: (id: string) => ['tools', id] as const,
  sprints: ['sprints'] as const,
  tasks: (sprintId?: string) => ['tasks', sprintId ?? 'all'] as const,
  task: (id: string) => ['task', id] as const,
  taskActivity: (id: string) => ['task', id, 'activity'] as const,
};
